### ISSUE TITLE
Could not load the chromosome id's for the chip data.

### ISSUE THREAD

**Issue by chrisclarkson** [gersteinlab/MUSIC#5]
Hi I am having some trouble with MUSIC.
I can not figure out if the package is pre-recognising that the files I have are already in SAM format and do not require pre-processing. I would save me a lot of processing time if I don't have to convert the files back to BAM files
Also is it possible that I can specify the paths directly to the input files rather than to the directories that contain them....?

ATTEMPT:
MUSIC -get_multiscale_broad_ERs -chip SAM1/ -control SAM2/ -mapp Mappability_36bp -l_mapp 36 -begin_l 1000 -end_l 16000 -step 1.5

## directories SAM1 and SAM2 both contain a single SAM file.
ERROR:
Could not load the chromosome id's for the chip data.

**Comment by harmancilab** [comment]
Hi Chris, I apologize this was not clear. You need to first preprocess the SAM file with MUSIC. It currently does not take SAM as an input. For this you can you the -preprocess option.

Let me know if you have other issues.

**Comment by chrisclarkson** [comment]
Hi,
Sorry I'm still unclear on this, I tried the following:

MUSIC -preprocess -get_multiscale_broad_ERs -chip SAM1 -control SAM2/ -mapp Mappability_36bp -l_mapp 36 -begin_l 1000 -end_l 16000 -step 1.5

Error:
USAGE: MUSIC -preprocess [File format ("SAM"/"ELAND"/"bowtie"/"tagAlign"/"BED5"/"BED6")] [Mapped reads file path ("stdin" for piped input)] [Output directory]

In which case I tried specifying a driectory:
MUSIC -preprocess SAM1 -get_multiscale_broad_ERs -chip SAM1 -control .SAM2/ -mapp Mappability_36bp -l_mapp 36 -begin_l 1000 -end_l 16000 -step 1.5

**Comment by harmancilab** [comment]
Hi Chris, I believe documentation is not very clear about this. MUSIC does not detect the sam files in a directory itself, so you need to specify them in the command line. Also, when you have a sam file you do not need to use "samtools view" because this command converts bam to sam and we don't need it when we already have a sam file. You can simply use the SAM file path. For example: 

MUSIC -preprocess SAM SAM1/AS-161148.sam chip

will preprocess AS-161148.sam and write the results to the directory named chip. Just to be clear; if you had a bam file, you would use:

samtools view SAM1/AS-161148.bam | MUSIC -preprocess SAM stdin chip

Above command would preprocess and write the results under directory chip.

..Back to SAM input file type case..

You can use a similar command for control data:

MUSIC -preprocess SAM  SAM1/AS-161148-input.sam control

I made up the name 'AS-161148-input.sam' to indicate the matching input DNA control library. You would have to use the actual name you assigned to the control library.

Then we can do sorting and dedup'ing for chip and control:
mkdir chip/sorted chip/dedup control/sorted control/dedup
MUSIC -sort_reads chip chip/sorted
MUSIC -remove_duplicates chip/sorted 2 chip/dedup
MUSIC -sort_reads control control/sorted
MUSIC -remove_duplicates control/sorted 2 control/dedup

Then finally we are ready to do ER calling:
MUSIC -preprocess -get_multiscale_broad_ERs -chip chip/dedup -control control/dedup -mapp Mappability_36bp -l_mapp 36 -begin_l 1000 -end_l 16000 -step 1.5

This should work for a while (40mins or so) and dump loads of files. The final ER calls are in a file named ERs.broadpeak.

Please make sure that mappability maps do exist under the directory 'Mappability_36bp'. If they are not there, music will issue a message saying it cannot find them and contiues without using the multi-mappability maps.

Hope this is clear. Please let me know if you have more questions.

Arif.

**Comment by ozgunharmanci** [comment]
Hi Chris, I believe documentation is not very clear about this. MUSIC does not detect the sam files in a directory itself, so you need to specify them in the command line. Also, when you have a sam file you do not need to use "samtools view" because this command converts bam to sam and we don't need it when we already have a sam file. You can simply use the SAM file path. For example:

MUSIC -preprocess SAM SAM1/AS-161148.sam chip

will preprocess AS-161148.sam and write the results to the directory named chip. Just to be clear; if you had a bam file, you would use:

samtools view SAM1/AS-161148.bam | MUSIC -preprocess SAM stdin chip

Above command would preprocess and write the results under directory chip.

..Back to SAM input file type case..

You can use a similar command for control data:

MUSIC -preprocess SAM SAM1/AS-161148-input.sam control

I made up the name 'AS-161148-input.sam' to indicate the matching input DNA control library. You would have to use the actual name you assigned to the control library.

Then we can do sorting and dedup'ing for chip and control:
mkdir chip/sorted chip/dedup control/sorted control/dedup
MUSIC -sort_reads chip chip/sorted
MUSIC -remove_duplicates chip/sorted 2 chip/dedup
MUSIC -sort_reads control control/sorted
MUSIC -remove_duplicates control/sorted 2 control/dedup

Then finally we are ready to do ER calling:
MUSIC -preprocess -get_multiscale_broad_ERs -chip chip/dedup -control control/dedup -mapp Mappability_36bp -l_mapp 36 -begin_l 1000 -end_l 16000 -step 1.5

This should work for a while (40mins or so) and dump loads of files. The final ER calls are in a file named ERs.broadpeak.

Please make sure that mappability maps do exist under the directory 'Mappability_36bp'. If they are not there, music will issue a message saying it cannot find them and contiues without using the multi-mappability maps.

Hope this is clear. Please let me know if you have more questions.

Arif.

**Comment by chrisclarkson** [comment]
Hi Again Arif,
Thank you for the reply- all of your instructions seemed to work both for the control and wt sample- except fro the very last step....

See that the deduped output in the wt folder is filled with content
ls -ltrh chip/dedup/
total 765M
-rw-rw----   63 Jul 18 14:12 chr_ids.txt
-rw-rw----   31M Jul 18 14:12 11_mapped_reads.txt
-rw-rw----   47M Jul 18 14:12 8_mapped_reads.txt
-rw-rw----   26M Jul 18 14:12 13_mapped_reads.txt
-rw-rw----   45M Jul 18 14:12 7_mapped_reads.txt
-rw-rw----   67M Jul 18 14:12 1_mapped_reads.txt
-rw-rw----   12M Jul 18 14:12 22_mapped_reads.txt
-rw-rw----   23M Jul 18 14:12 15_mapped_reads.txt
-rw-rw----   16M Jul 18 14:12 20_mapped_reads.txt
-rw-rw----   23M Jul 18 14:12 19_mapped_reads.txt
-rw-rw----   31M Jul 18 14:12 9_mapped_reads.txt
-rw-rw----   38M Jul 18 14:12 5_mapped_reads.txt
-rw-rw----   55M Jul 18 14:12 6_mapped_reads.txt
-rw-rw----   62M Jul 18 14:12 2_mapped_reads.txt
-rw-rw----   46M Jul 18 14:12 3_mapped_reads.txt
-rw-rw----   11M Jul 18 14:12 21_mapped_reads.txt
-rw-rw----   17M Jul 18 14:12 18_mapped_reads.txt
-rw-rw----   38M Jul 18 14:12 12_mapped_reads.txt
-rw-rw----   50M Jul 18 14:12 4_mapped_reads.txt
-rw-rw----   26M Jul 18 14:12 16_mapped_reads.txt
-rw-rw----   23M Jul 18 14:12 17_mapped_reads.txt
-rw-rw----   26M Jul 18 14:13 X_mapped_reads.txt
-rw-rw----   23M Jul 18 14:13 14_mapped_reads.txt
-rw-rw----   37M Jul 18 14:13 10_mapped_reads.txt
-rw-rw----   1.7M Jul 18 14:13 Y_mapped_reads.txt
-rw-rw----   392K Jul 18 14:13 M_mapped_reads.txt

However these data are not processable for some reason:

MUSIC -preprocess -get_multiscale_broad_ERs -chip chip/dedup/ -control /storage/projects/teif/mESC/chris_calculations/H1_Linker_data/playxx/AS-161142-LR-23150/fastq/chip/dedup/ -mapp Mappability_36bp -l_mapp 36 -begin_l 1000 -end_l 16000 -step 1.5

ERROR:
USAGE: MUSIC -preprocess [File format ("SAM"/"ELAND"/"bowtie"/"tagAlign"/"BED5"/"BED6")] [Mapped reads file path ("stdin" for piped input)] [Output directory]

I also tried piping all of this to an output file/directory- with '> out' at the end of the command but I got the same error...

**Comment by ozgunharmanci** [comment]
You need to specify only one option:
MUSIC **-get_multiscale_broad_ERs** -chip chip/dedup/ -control /storage/projects/...

insted of 
MUSIC **-preprocess -get_multiscale_broad_ERs** -chip chip/dedup/ -control /storage/projects/...
